### ISSUE TITLE
Next Road Map

### ISSUE THREAD

**Issue by KeenS** [KeenS/webml#14]
# External
* [x] implement pattern match #26
  + ~~in MVP, tuple pattern match~~
* [x] implement ADT #25
# Internal
* [x] treat (user-facing) binops as usual functions in HIR. #27
  + perhaps it requires to prepare user-facing function and internal operators
* [x] write tests and run it on CI
  + [x] parser
  + [x]  typecheck
  + [x] exhausitiveness check of patterns
  + [x] compile pass

**Comment by KeenS** [comment]
some tasks are partially done, but we go next road map
